version: '3.8'

services:

  web1:
    build: .
    ports:
      - "9091:80"

    depends_on:
      - db1

  db1:
    image: mysql:8

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: password123

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
   mysql_data:
